# Generated by Django 4.2.8 on 2023-12-26 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='date_creation',
            field=models.DateField(default=datetime.date.today, verbose_name='Date Creation'),
        ),
        migrations.AddField(
            model_name='company',
            name='last_modified',
            field=models.DateField(default=datetime.date.today, verbose_name='Last Modified'),
        ),
    ]
