# Generated by Django 4.2.8 on 2023-12-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_options_company_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date_creation',
            field=models.DateField(auto_now_add=True, verbose_name='Date Creation'),
        ),
        migrations.AlterField(
            model_name='company',
            name='last_modified',
            field=models.DateField(auto_now_add=True, verbose_name='Last Modified'),
        ),
    ]
