# Generated by Django 4.2.8 on 2023-12-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_openposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='openposition',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Description'),
        ),
    ]
